# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(533, 360)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(59, 149, 370, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_buttons_and_time = QtWidgets.QHBoxLayout()
        self.horizontalLayout_buttons_and_time.setObjectName("horizontalLayout_buttons_and_time")
        self.lable_date = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(49)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lable_date.sizePolicy().hasHeightForWidth())
        self.lable_date.setSizePolicy(sizePolicy)
        self.lable_date.setMinimumSize(QtCore.QSize(0, 0))
        self.lable_date.setSizeIncrement(QtCore.QSize(0, 0))
        self.lable_date.setBaseSize(QtCore.QSize(0, 0))
        self.lable_date.setText("")
        self.lable_date.setObjectName("lable_date")
        self.horizontalLayout_buttons_and_time.addWidget(self.lable_date)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_delete_task = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_delete_task.sizePolicy().hasHeightForWidth())
        self.btn_delete_task.setSizePolicy(sizePolicy)
        self.btn_delete_task.setObjectName("btn_delete_task")
        self.horizontalLayout.addWidget(self.btn_delete_task)
        self.btn_edit_task = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_edit_task.sizePolicy().hasHeightForWidth())
        self.btn_edit_task.setSizePolicy(sizePolicy)
        self.btn_edit_task.setObjectName("btn_edit_task")
        self.horizontalLayout.addWidget(self.btn_edit_task)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.radbtn_mute = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radbtn_mute.sizePolicy().hasHeightForWidth())
        self.radbtn_mute.setSizePolicy(sizePolicy)
        self.radbtn_mute.setObjectName("radbtn_mute")
        self.verticalLayout_2.addWidget(self.radbtn_mute)
        self.horizontalLayout_buttons_and_time.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_buttons_and_time)
        self.lable_discription = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.lable_discription.setMinimumSize(QtCore.QSize(0, 0))
        self.lable_discription.setText("")
        self.lable_discription.setObjectName("lable_discription")
        self.verticalLayout.addWidget(self.lable_discription)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_delete_task.setText(_translate("Form", "Delete"))
        self.btn_edit_task.setText(_translate("Form", "Edit"))
        self.radbtn_mute.setText(_translate("Form", "Mute"))
